/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as SupplyRequestsRouteImport } from './routes/supply-requests'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyRequestsRoute = SupplyRequestsRouteImport.update({
  id: '/supply-requests',
  path: '/supply-requests',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/properties': typeof PropertiesRoute
  '/reservations': typeof ReservationsRoute
  '/submissions': typeof SubmissionsRoute
  '/supply-requests': typeof SupplyRequestsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/properties': typeof PropertiesRoute
  '/reservations': typeof ReservationsRoute
  '/submissions': typeof SubmissionsRoute
  '/supply-requests': typeof SupplyRequestsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/properties': typeof PropertiesRoute
  '/reservations': typeof ReservationsRoute
  '/submissions': typeof SubmissionsRoute
  '/supply-requests': typeof SupplyRequestsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/properties' | '/reservations' | '/submissions' | '/supply-requests'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/properties' | '/reservations' | '/submissions' | '/supply-requests'
  id:
    | '__root__'
    | '/'
    | '/properties'
    | '/reservations'
    | '/submissions'
    | '/supply-requests'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PropertiesRoute: typeof PropertiesRoute
  ReservationsRoute: typeof ReservationsRoute
  SubmissionsRoute: typeof SubmissionsRoute
  SupplyRequestsRoute: typeof SupplyRequestsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply-requests': {
      id: '/supply-requests'
      path: '/supply-requests'
      fullPath: '/supply-requests'
      preLoaderRoute: typeof SupplyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PropertiesRoute: PropertiesRoute,
  ReservationsRoute: ReservationsRoute,
  SubmissionsRoute: SubmissionsRoute,
  SupplyRequestsRoute: SupplyRequestsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
