/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as InvoicesRouteImport } from './routes/invoices'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as PropertiesRouteImport } from './routes/properties'
import { Route as ReservationsRouteImport } from './routes/reservations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SubmissionsRouteImport } from './routes/submissions'
import { Route as SupplyRequestsRouteImport } from './routes/supply-requests'
import { Route as TasksRouteImport } from './routes/tasks'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesRoute = InvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertiesRoute = PropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservationsRoute = ReservationsRouteImport.update({
  id: '/reservations',
  path: '/reservations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SubmissionsRoute = SubmissionsRouteImport.update({
  id: '/submissions',
  path: '/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplyRequestsRoute = SupplyRequestsRouteImport.update({
  id: '/supply-requests',
  path: '/supply-requests',
  getParentRoute: () => rootRouteImport,
} as any)
const TasksRoute = TasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/invoices': typeof InvoicesRoute
  '/owners': typeof OwnersRoute
  '/properties': typeof PropertiesRoute
  '/reservations': typeof ReservationsRoute
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRoute
  '/supply-requests': typeof SupplyRequestsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/invoices': typeof InvoicesRoute
  '/owners': typeof OwnersRoute
  '/properties': typeof PropertiesRoute
  '/reservations': typeof ReservationsRoute
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRoute
  '/supply-requests': typeof SupplyRequestsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contracts': typeof ContractsRoute
  '/invoices': typeof InvoicesRoute
  '/owners': typeof OwnersRoute
  '/properties': typeof PropertiesRoute
  '/reservations': typeof ReservationsRoute
  '/settings': typeof SettingsRoute
  '/submissions': typeof SubmissionsRoute
  '/supply-requests': typeof SupplyRequestsRoute
  '/tasks': typeof TasksRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contracts'
    | '/invoices'
    | '/owners'
    | '/properties'
    | '/reservations'
    | '/settings'
    | '/submissions'
    | '/supply-requests'
    | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contracts'
    | '/invoices'
    | '/owners'
    | '/properties'
    | '/reservations'
    | '/settings'
    | '/submissions'
    | '/supply-requests'
    | '/tasks'
  id:
    | '__root__'
    | '/'
    | '/contracts'
    | '/invoices'
    | '/owners'
    | '/properties'
    | '/reservations'
    | '/settings'
    | '/submissions'
    | '/supply-requests'
    | '/tasks'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContractsRoute: typeof ContractsRoute
  InvoicesRoute: typeof InvoicesRoute
  OwnersRoute: typeof OwnersRoute
  PropertiesRoute: typeof PropertiesRoute
  ReservationsRoute: typeof ReservationsRoute
  SettingsRoute: typeof SettingsRoute
  SubmissionsRoute: typeof SubmissionsRoute
  SupplyRequestsRoute: typeof SupplyRequestsRoute
  TasksRoute: typeof TasksRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices': {
      id: '/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof InvoicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/properties': {
      id: '/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof PropertiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservations': {
      id: '/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof ReservationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/submissions': {
      id: '/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof SubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supply-requests': {
      id: '/supply-requests'
      path: '/supply-requests'
      fullPath: '/supply-requests'
      preLoaderRoute: typeof SupplyRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tasks': {
      id: '/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof TasksRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContractsRoute: ContractsRoute,
  InvoicesRoute: InvoicesRoute,
  OwnersRoute: OwnersRoute,
  PropertiesRoute: PropertiesRoute,
  ReservationsRoute: ReservationsRoute,
  SettingsRoute: SettingsRoute,
  SubmissionsRoute: SubmissionsRoute,
  SupplyRequestsRoute: SupplyRequestsRoute,
  TasksRoute: TasksRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
