/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as RentRouteImport } from './routes/rent'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as AuthenticatedActivitiesRouteImport } from './routes/_authenticated/activities'
import { Route as AuthenticatedActivityLogRouteImport } from './routes/_authenticated/activity-log'
import { Route as AuthenticatedClientsRouteImport } from './routes/_authenticated/clients'
import { Route as AuthenticatedContractImportsRouteImport } from './routes/_authenticated/contract-imports'
import { Route as AuthenticatedContractsRouteImport } from './routes/_authenticated/contracts'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedEmployeesRouteImport } from './routes/_authenticated/employees'
import { Route as AuthenticatedErrorLogRouteImport } from './routes/_authenticated/error-log'
import { Route as AuthenticatedInvoicesRouteImport } from './routes/_authenticated/invoices'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedOpportunitiesRouteImport } from './routes/_authenticated/opportunities'
import { Route as AuthenticatedOwnersRouteImport } from './routes/_authenticated/owners'
import { Route as AuthenticatedPartnersRouteImport } from './routes/_authenticated/partners'
import { Route as AuthenticatedPropertiesRouteImport } from './routes/_authenticated/properties'
import { Route as AuthenticatedRemindersRouteImport } from './routes/_authenticated/reminders'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedReservationsRouteImport } from './routes/_authenticated/reservations'
import { Route as AuthenticatedRolesRouteImport } from './routes/_authenticated/roles'
import { Route as AuthenticatedServicesRouteImport } from './routes/_authenticated/services'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedSubmissionsRouteImport } from './routes/_authenticated/submissions'
import { Route as AuthenticatedSupplyRequestsRouteImport } from './routes/_authenticated/supply-requests'
import { Route as AuthenticatedTasksRouteImport } from './routes/_authenticated/tasks'
import { Route as PropertiesCodeRouteImport } from './routes/properties.$code'
import { Route as AuthenticatedTasksNormalRouteImport } from './routes/_authenticated/tasks.normal'
import { Route as AuthenticatedTasksPhotographyRouteImport } from './routes/_authenticated/tasks.photography'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const RentRoute = RentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedActivitiesRoute = AuthenticatedActivitiesRouteImport.update({
  id: '/activities',
  path: '/activities',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedActivityLogRoute =
  AuthenticatedActivityLogRouteImport.update({
    id: '/activity-log',
    path: '/activity-log',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClientsRoute = AuthenticatedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractImportsRoute =
  AuthenticatedContractImportsRouteImport.update({
    id: '/contract-imports',
    path: '/contract-imports',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedContractsRoute = AuthenticatedContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmployeesRoute = AuthenticatedEmployeesRouteImport.update({
  id: '/employees',
  path: '/employees',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedErrorLogRoute = AuthenticatedErrorLogRouteImport.update({
  id: '/error-log',
  path: '/error-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInvoicesRoute = AuthenticatedInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOpportunitiesRoute =
  AuthenticatedOpportunitiesRouteImport.update({
    id: '/opportunities',
    path: '/opportunities',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedOwnersRoute = AuthenticatedOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPartnersRoute = AuthenticatedPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertiesRoute = AuthenticatedPropertiesRouteImport.update({
  id: '/properties',
  path: '/properties',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRemindersRoute = AuthenticatedRemindersRouteImport.update({
  id: '/reminders',
  path: '/reminders',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReservationsRoute =
  AuthenticatedReservationsRouteImport.update({
    id: '/reservations',
    path: '/reservations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedRolesRoute = AuthenticatedRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedServicesRoute = AuthenticatedServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSubmissionsRoute =
  AuthenticatedSubmissionsRouteImport.update({
    id: '/submissions',
    path: '/submissions',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedSupplyRequestsRoute =
  AuthenticatedSupplyRequestsRouteImport.update({
    id: '/supply-requests',
    path: '/supply-requests',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedTasksRoute = AuthenticatedTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const PropertiesCodeRoute = PropertiesCodeRouteImport.update({
  id: '/properties/$code',
  path: '/properties/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTasksNormalRoute =
  AuthenticatedTasksNormalRouteImport.update({
    id: '/normal',
    path: '/normal',
    getParentRoute: () => AuthenticatedTasksRoute,
  } as any)
const AuthenticatedTasksPhotographyRoute =
  AuthenticatedTasksPhotographyRouteImport.update({
    id: '/photography',
    path: '/photography',
    getParentRoute: () => AuthenticatedTasksRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/rent': typeof RentRoute
  '/sale': typeof SaleRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/contract-imports': typeof AuthenticatedContractImportsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/error-log': typeof AuthenticatedErrorLogRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/owners': typeof AuthenticatedOwnersRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/supply-requests': typeof AuthenticatedSupplyRequestsRoute
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/properties/$code': typeof PropertiesCodeRoute
  '/tasks/normal': typeof AuthenticatedTasksNormalRoute
  '/tasks/photography': typeof AuthenticatedTasksPhotographyRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/rent': typeof RentRoute
  '/sale': typeof SaleRoute
  '/activities': typeof AuthenticatedActivitiesRoute
  '/activity-log': typeof AuthenticatedActivityLogRoute
  '/clients': typeof AuthenticatedClientsRoute
  '/contract-imports': typeof AuthenticatedContractImportsRoute
  '/contracts': typeof AuthenticatedContractsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/employees': typeof AuthenticatedEmployeesRoute
  '/error-log': typeof AuthenticatedErrorLogRoute
  '/invoices': typeof AuthenticatedInvoicesRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/owners': typeof AuthenticatedOwnersRoute
  '/partners': typeof AuthenticatedPartnersRoute
  '/properties': typeof AuthenticatedPropertiesRoute
  '/reminders': typeof AuthenticatedRemindersRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/reservations': typeof AuthenticatedReservationsRoute
  '/roles': typeof AuthenticatedRolesRoute
  '/services': typeof AuthenticatedServicesRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/submissions': typeof AuthenticatedSubmissionsRoute
  '/supply-requests': typeof AuthenticatedSupplyRequestsRoute
  '/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/properties/$code': typeof PropertiesCodeRoute
  '/tasks/normal': typeof AuthenticatedTasksNormalRoute
  '/tasks/photography': typeof AuthenticatedTasksPhotographyRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/about': typeof AboutRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/rent': typeof RentRoute
  '/sale': typeof SaleRoute
  '/_authenticated/activities': typeof AuthenticatedActivitiesRoute
  '/_authenticated/activity-log': typeof AuthenticatedActivityLogRoute
  '/_authenticated/clients': typeof AuthenticatedClientsRoute
  '/_authenticated/contract-imports': typeof AuthenticatedContractImportsRoute
  '/_authenticated/contracts': typeof AuthenticatedContractsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/employees': typeof AuthenticatedEmployeesRoute
  '/_authenticated/error-log': typeof AuthenticatedErrorLogRoute
  '/_authenticated/invoices': typeof AuthenticatedInvoicesRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/opportunities': typeof AuthenticatedOpportunitiesRoute
  '/_authenticated/owners': typeof AuthenticatedOwnersRoute
  '/_authenticated/partners': typeof AuthenticatedPartnersRoute
  '/_authenticated/properties': typeof AuthenticatedPropertiesRoute
  '/_authenticated/reminders': typeof AuthenticatedRemindersRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/reservations': typeof AuthenticatedReservationsRoute
  '/_authenticated/roles': typeof AuthenticatedRolesRoute
  '/_authenticated/services': typeof AuthenticatedServicesRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/_authenticated/submissions': typeof AuthenticatedSubmissionsRoute
  '/_authenticated/supply-requests': typeof AuthenticatedSupplyRequestsRoute
  '/_authenticated/tasks': typeof AuthenticatedTasksRouteWithChildren
  '/properties/$code': typeof PropertiesCodeRoute
  '/_authenticated/tasks/normal': typeof AuthenticatedTasksNormalRoute
  '/_authenticated/tasks/photography': typeof AuthenticatedTasksPhotographyRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/rent'
    | '/sale'
    | '/activities'
    | '/activity-log'
    | '/clients'
    | '/contract-imports'
    | '/contracts'
    | '/dashboard'
    | '/employees'
    | '/error-log'
    | '/invoices'
    | '/notifications'
    | '/opportunities'
    | '/owners'
    | '/partners'
    | '/properties'
    | '/reminders'
    | '/reports'
    | '/reservations'
    | '/roles'
    | '/services'
    | '/settings'
    | '/submissions'
    | '/supply-requests'
    | '/tasks'
    | '/properties/$code'
    | '/tasks/normal'
    | '/tasks/photography'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/auth'
    | '/contact'
    | '/rent'
    | '/sale'
    | '/activities'
    | '/activity-log'
    | '/clients'
    | '/contract-imports'
    | '/contracts'
    | '/dashboard'
    | '/employees'
    | '/error-log'
    | '/invoices'
    | '/notifications'
    | '/opportunities'
    | '/owners'
    | '/partners'
    | '/properties'
    | '/reminders'
    | '/reports'
    | '/reservations'
    | '/roles'
    | '/services'
    | '/settings'
    | '/submissions'
    | '/supply-requests'
    | '/tasks'
    | '/properties/$code'
    | '/tasks/normal'
    | '/tasks/photography'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/about'
    | '/auth'
    | '/contact'
    | '/rent'
    | '/sale'
    | '/_authenticated/activities'
    | '/_authenticated/activity-log'
    | '/_authenticated/clients'
    | '/_authenticated/contract-imports'
    | '/_authenticated/contracts'
    | '/_authenticated/dashboard'
    | '/_authenticated/employees'
    | '/_authenticated/error-log'
    | '/_authenticated/invoices'
    | '/_authenticated/notifications'
    | '/_authenticated/opportunities'
    | '/_authenticated/owners'
    | '/_authenticated/partners'
    | '/_authenticated/properties'
    | '/_authenticated/reminders'
    | '/_authenticated/reports'
    | '/_authenticated/reservations'
    | '/_authenticated/roles'
    | '/_authenticated/services'
    | '/_authenticated/settings'
    | '/_authenticated/submissions'
    | '/_authenticated/supply-requests'
    | '/_authenticated/tasks'
    | '/properties/$code'
    | '/_authenticated/tasks/normal'
    | '/_authenticated/tasks/photography'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AboutRoute: typeof AboutRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  RentRoute: typeof RentRoute
  SaleRoute: typeof SaleRoute
  PropertiesCodeRoute: typeof PropertiesCodeRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rent': {
      id: '/rent'
      path: '/rent'
      fullPath: '/rent'
      preLoaderRoute: typeof RentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/activities': {
      id: '/_authenticated/activities'
      path: '/activities'
      fullPath: '/activities'
      preLoaderRoute: typeof AuthenticatedActivitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/activity-log': {
      id: '/_authenticated/activity-log'
      path: '/activity-log'
      fullPath: '/activity-log'
      preLoaderRoute: typeof AuthenticatedActivityLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/clients': {
      id: '/_authenticated/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthenticatedClientsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contract-imports': {
      id: '/_authenticated/contract-imports'
      path: '/contract-imports'
      fullPath: '/contract-imports'
      preLoaderRoute: typeof AuthenticatedContractImportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contracts': {
      id: '/_authenticated/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof AuthenticatedContractsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/employees': {
      id: '/_authenticated/employees'
      path: '/employees'
      fullPath: '/employees'
      preLoaderRoute: typeof AuthenticatedEmployeesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/error-log': {
      id: '/_authenticated/error-log'
      path: '/error-log'
      fullPath: '/error-log'
      preLoaderRoute: typeof AuthenticatedErrorLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/invoices': {
      id: '/_authenticated/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AuthenticatedInvoicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/opportunities': {
      id: '/_authenticated/opportunities'
      path: '/opportunities'
      fullPath: '/opportunities'
      preLoaderRoute: typeof AuthenticatedOpportunitiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/owners': {
      id: '/_authenticated/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof AuthenticatedOwnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/partners': {
      id: '/_authenticated/partners'
      path: '/partners'
      fullPath: '/partners'
      preLoaderRoute: typeof AuthenticatedPartnersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/properties': {
      id: '/_authenticated/properties'
      path: '/properties'
      fullPath: '/properties'
      preLoaderRoute: typeof AuthenticatedPropertiesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reminders': {
      id: '/_authenticated/reminders'
      path: '/reminders'
      fullPath: '/reminders'
      preLoaderRoute: typeof AuthenticatedRemindersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reservations': {
      id: '/_authenticated/reservations'
      path: '/reservations'
      fullPath: '/reservations'
      preLoaderRoute: typeof AuthenticatedReservationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/roles': {
      id: '/_authenticated/roles'
      path: '/roles'
      fullPath: '/roles'
      preLoaderRoute: typeof AuthenticatedRolesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/services': {
      id: '/_authenticated/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof AuthenticatedServicesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/submissions': {
      id: '/_authenticated/submissions'
      path: '/submissions'
      fullPath: '/submissions'
      preLoaderRoute: typeof AuthenticatedSubmissionsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/supply-requests': {
      id: '/_authenticated/supply-requests'
      path: '/supply-requests'
      fullPath: '/supply-requests'
      preLoaderRoute: typeof AuthenticatedSupplyRequestsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/tasks': {
      id: '/_authenticated/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AuthenticatedTasksRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/properties/$code': {
      id: '/properties/$code'
      path: '/properties/$code'
      fullPath: '/properties/$code'
      preLoaderRoute: typeof PropertiesCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/tasks/normal': {
      id: '/_authenticated/tasks/normal'
      path: '/normal'
      fullPath: '/tasks/normal'
      preLoaderRoute: typeof AuthenticatedTasksNormalRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
    '/_authenticated/tasks/photography': {
      id: '/_authenticated/tasks/photography'
      path: '/photography'
      fullPath: '/tasks/photography'
      preLoaderRoute: typeof AuthenticatedTasksPhotographyRouteImport
      parentRoute: typeof AuthenticatedTasksRoute
    }
  }
}

interface AuthenticatedTasksRouteChildren {
  AuthenticatedTasksNormalRoute: typeof AuthenticatedTasksNormalRoute
  AuthenticatedTasksPhotographyRoute: typeof AuthenticatedTasksPhotographyRoute
}

const AuthenticatedTasksRouteChildren: AuthenticatedTasksRouteChildren = {
  AuthenticatedTasksNormalRoute: AuthenticatedTasksNormalRoute,
  AuthenticatedTasksPhotographyRoute: AuthenticatedTasksPhotographyRoute,
}

const AuthenticatedTasksRouteWithChildren =
  AuthenticatedTasksRoute._addFileChildren(AuthenticatedTasksRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedActivitiesRoute: typeof AuthenticatedActivitiesRoute
  AuthenticatedActivityLogRoute: typeof AuthenticatedActivityLogRoute
  AuthenticatedClientsRoute: typeof AuthenticatedClientsRoute
  AuthenticatedContractImportsRoute: typeof AuthenticatedContractImportsRoute
  AuthenticatedContractsRoute: typeof AuthenticatedContractsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmployeesRoute: typeof AuthenticatedEmployeesRoute
  AuthenticatedErrorLogRoute: typeof AuthenticatedErrorLogRoute
  AuthenticatedInvoicesRoute: typeof AuthenticatedInvoicesRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedOpportunitiesRoute: typeof AuthenticatedOpportunitiesRoute
  AuthenticatedOwnersRoute: typeof AuthenticatedOwnersRoute
  AuthenticatedPartnersRoute: typeof AuthenticatedPartnersRoute
  AuthenticatedPropertiesRoute: typeof AuthenticatedPropertiesRoute
  AuthenticatedRemindersRoute: typeof AuthenticatedRemindersRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedReservationsRoute: typeof AuthenticatedReservationsRoute
  AuthenticatedRolesRoute: typeof AuthenticatedRolesRoute
  AuthenticatedServicesRoute: typeof AuthenticatedServicesRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedSubmissionsRoute: typeof AuthenticatedSubmissionsRoute
  AuthenticatedSupplyRequestsRoute: typeof AuthenticatedSupplyRequestsRoute
  AuthenticatedTasksRoute: typeof AuthenticatedTasksRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedActivitiesRoute: AuthenticatedActivitiesRoute,
  AuthenticatedActivityLogRoute: AuthenticatedActivityLogRoute,
  AuthenticatedClientsRoute: AuthenticatedClientsRoute,
  AuthenticatedContractImportsRoute: AuthenticatedContractImportsRoute,
  AuthenticatedContractsRoute: AuthenticatedContractsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmployeesRoute: AuthenticatedEmployeesRoute,
  AuthenticatedErrorLogRoute: AuthenticatedErrorLogRoute,
  AuthenticatedInvoicesRoute: AuthenticatedInvoicesRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedOpportunitiesRoute: AuthenticatedOpportunitiesRoute,
  AuthenticatedOwnersRoute: AuthenticatedOwnersRoute,
  AuthenticatedPartnersRoute: AuthenticatedPartnersRoute,
  AuthenticatedPropertiesRoute: AuthenticatedPropertiesRoute,
  AuthenticatedRemindersRoute: AuthenticatedRemindersRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedReservationsRoute: AuthenticatedReservationsRoute,
  AuthenticatedRolesRoute: AuthenticatedRolesRoute,
  AuthenticatedServicesRoute: AuthenticatedServicesRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedSubmissionsRoute: AuthenticatedSubmissionsRoute,
  AuthenticatedSupplyRequestsRoute: AuthenticatedSupplyRequestsRoute,
  AuthenticatedTasksRoute: AuthenticatedTasksRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AboutRoute: AboutRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  RentRoute: RentRoute,
  SaleRoute: SaleRoute,
  PropertiesCodeRoute: PropertiesCodeRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
